[package]
name = "reddit"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bytes = "1.11.1"
chrono = { version = "0.4", features = ["serde"] }
clap = "4.5.23"
dotenv = "0.15.0"
eyre = "0.6"
reqwest = { version = "0.13", features = ["query", "form"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_path_to_error = "0.1"
thiserror = "1.0.62"
tokio = { version = "1.0", features = ["rt-multi-thread", "time", "macros", "process"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["chrono"] }
url = "2.5.8"

